sudo: false
dist: xenial
language: cpp
compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
        - libopenal-dev
    - libjpeg-dev
    - libudev-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libvorbis-dev
    - libflac-dev
    - g++-8
    - gcc-8


before_install:
- git clone https://github.com/SFML/SFML.git
- cd SFML
- curl https://gitlab.peach-bun.com/pinion/SFML/commit/3383b4a472f0bd16a8161fb8760cd3e6333f1782.patch | patch -p1

- mkdir cmake-dist
- travis_retry wget -qO- https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.tar.gz | sudo tar --strip-components=1 -C cmake-dist -xz 
- export PATH=$PWD/cmake-dist/bin:$PATH;

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi

script:
  - mkdir build
  - cd build
  - gcc -v && g++ -v && cmake --version
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
