sudo: false
dist: xenial
language: cpp
compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
    - gcc-8


before_install:
- sudo apt-get install -y libjpeg62-dev libsfml-dev libsndfile1-dev libglew1.5 libglew1.5-dev libfreetype6 libjpeg-turbo8 libjpeg8 libopenal-data libopenal1  libxrandr2 libxrender1 libsoil1

- mkdir cmake-dist
- travis_retry wget -qO- https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.tar.gz | sudo tar --strip-components=1 -C cmake-dist -xz 
- export PATH=$PWD/cmake-dist/bin:$PATH;

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi

script:
  - mkdir build
  - cd build
  - gcc -v && g++ -v && cmake --version
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
